In [4]:
import tensorflow as tf

In [11]:
print(tf.__version__)
t = tf.random.uniform([2,3],0,1)
print(a)
print(type(a))

2.4.1
tf.Tensor(
[[0.13017702 0.09202707 0.05720556]
 [0.7577729  0.4890324  0.8850335 ]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [12]:
import numpy as np

In [13]:
n = np.random.uniform(0,1,[2,3])

In [15]:
print("tensorflow로 생성한 텐서:\n", t, "\n")
print("numpy로 생성한 ndarray\n", n, "\n")

res = t + n
print("덧셈 결과: \n", res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.25961637 0.09932053 0.6072885 ]
 [0.78393376 0.3545419  0.23833656]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray
 [[0.4659103  0.58333647 0.21341782]
 [0.09038523 0.36990483 0.56652918]] 

덧셈 결과: 
 tf.Tensor(
[[0.7255267 0.682657  0.8207063]
 [0.874319  0.7244467 0.8048657]], shape=(2, 3), dtype=float32)
